/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroAcademiaRouteImport } from './routes/cadastro-academia'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTurmasRouteImport } from './routes/_authenticated/turmas'
import { Route as AuthenticatedPresencaRouteImport } from './routes/_authenticated/presenca'
import { Route as AuthenticatedInstrutoresRouteImport } from './routes/_authenticated/instrutores'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAfiliacoesRouteImport } from './routes/_authenticated/afiliacoes'
import { Route as AuthenticatedRelatoriosIndexRouteImport } from './routes/_authenticated/relatorios/index'
import { Route as AuthenticatedAlunosIndexRouteImport } from './routes/_authenticated/alunos.index'
import { Route as ApiPublicCheckGraduationAlertsRouteImport } from './routes/api/public/check-graduation-alerts'
import { Route as AuthenticatedFinanceiroMensalidadesRouteImport } from './routes/_authenticated/financeiro.mensalidades'
import { Route as AuthenticatedAlunosNovoRouteImport } from './routes/_authenticated/alunos.novo'
import { Route as AuthenticatedAlunosAlunoIdRouteImport } from './routes/_authenticated/alunos.$alunoId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAcademiaRoute = CadastroAcademiaRouteImport.update({
  id: '/cadastro-academia',
  path: '/cadastro-academia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTurmasRoute = AuthenticatedTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPresencaRoute = AuthenticatedPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstrutoresRoute =
  AuthenticatedInstrutoresRouteImport.update({
    id: '/instrutores',
    path: '/instrutores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAfiliacoesRoute = AuthenticatedAfiliacoesRouteImport.update({
  id: '/afiliacoes',
  path: '/afiliacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosIndexRoute =
  AuthenticatedRelatoriosIndexRouteImport.update({
    id: '/relatorios/',
    path: '/relatorios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAlunosIndexRoute =
  AuthenticatedAlunosIndexRouteImport.update({
    id: '/alunos/',
    path: '/alunos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicCheckGraduationAlertsRoute =
  ApiPublicCheckGraduationAlertsRouteImport.update({
    id: '/api/public/check-graduation-alerts',
    path: '/api/public/check-graduation-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFinanceiroMensalidadesRoute =
  AuthenticatedFinanceiroMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedAlunosNovoRoute = AuthenticatedAlunosNovoRouteImport.update({
  id: '/alunos/novo',
  path: '/alunos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlunosAlunoIdRoute =
  AuthenticatedAlunosAlunoIdRouteImport.update({
    id: '/alunos/$alunoId',
    path: '/alunos/$alunoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro-academia': typeof CadastroAcademiaRoute
  '/login': typeof LoginRoute
  '/afiliacoes': typeof AuthenticatedAfiliacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/instrutores': typeof AuthenticatedInstrutoresRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/turmas': typeof AuthenticatedTurmasRoute
  '/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/financeiro/mensalidades': typeof AuthenticatedFinanceiroMensalidadesRoute
  '/api/public/check-graduation-alerts': typeof ApiPublicCheckGraduationAlertsRoute
  '/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro-academia': typeof CadastroAcademiaRoute
  '/login': typeof LoginRoute
  '/afiliacoes': typeof AuthenticatedAfiliacoesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/instrutores': typeof AuthenticatedInstrutoresRoute
  '/presenca': typeof AuthenticatedPresencaRoute
  '/turmas': typeof AuthenticatedTurmasRoute
  '/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/financeiro/mensalidades': typeof AuthenticatedFinanceiroMensalidadesRoute
  '/api/public/check-graduation-alerts': typeof ApiPublicCheckGraduationAlertsRoute
  '/alunos': typeof AuthenticatedAlunosIndexRoute
  '/relatorios': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro-academia': typeof CadastroAcademiaRoute
  '/login': typeof LoginRoute
  '/_authenticated/afiliacoes': typeof AuthenticatedAfiliacoesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/instrutores': typeof AuthenticatedInstrutoresRoute
  '/_authenticated/presenca': typeof AuthenticatedPresencaRoute
  '/_authenticated/turmas': typeof AuthenticatedTurmasRoute
  '/_authenticated/alunos/$alunoId': typeof AuthenticatedAlunosAlunoIdRoute
  '/_authenticated/alunos/novo': typeof AuthenticatedAlunosNovoRoute
  '/_authenticated/financeiro/mensalidades': typeof AuthenticatedFinanceiroMensalidadesRoute
  '/api/public/check-graduation-alerts': typeof ApiPublicCheckGraduationAlertsRoute
  '/_authenticated/alunos/': typeof AuthenticatedAlunosIndexRoute
  '/_authenticated/relatorios/': typeof AuthenticatedRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro-academia'
    | '/login'
    | '/afiliacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/instrutores'
    | '/presenca'
    | '/turmas'
    | '/alunos/$alunoId'
    | '/alunos/novo'
    | '/financeiro/mensalidades'
    | '/api/public/check-graduation-alerts'
    | '/alunos/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro-academia'
    | '/login'
    | '/afiliacoes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/instrutores'
    | '/presenca'
    | '/turmas'
    | '/alunos/$alunoId'
    | '/alunos/novo'
    | '/financeiro/mensalidades'
    | '/api/public/check-graduation-alerts'
    | '/alunos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro-academia'
    | '/login'
    | '/_authenticated/afiliacoes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/instrutores'
    | '/_authenticated/presenca'
    | '/_authenticated/turmas'
    | '/_authenticated/alunos/$alunoId'
    | '/_authenticated/alunos/novo'
    | '/_authenticated/financeiro/mensalidades'
    | '/api/public/check-graduation-alerts'
    | '/_authenticated/alunos/'
    | '/_authenticated/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroAcademiaRoute: typeof CadastroAcademiaRoute
  LoginRoute: typeof LoginRoute
  ApiPublicCheckGraduationAlertsRoute: typeof ApiPublicCheckGraduationAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-academia': {
      id: '/cadastro-academia'
      path: '/cadastro-academia'
      fullPath: '/cadastro-academia'
      preLoaderRoute: typeof CadastroAcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/turmas': {
      id: '/_authenticated/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AuthenticatedTurmasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presenca': {
      id: '/_authenticated/presenca'
      path: '/presenca'
      fullPath: '/presenca'
      preLoaderRoute: typeof AuthenticatedPresencaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instrutores': {
      id: '/_authenticated/instrutores'
      path: '/instrutores'
      fullPath: '/instrutores'
      preLoaderRoute: typeof AuthenticatedInstrutoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/afiliacoes': {
      id: '/_authenticated/afiliacoes'
      path: '/afiliacoes'
      fullPath: '/afiliacoes'
      preLoaderRoute: typeof AuthenticatedAfiliacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios/': {
      id: '/_authenticated/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AuthenticatedRelatoriosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/': {
      id: '/_authenticated/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AuthenticatedAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/check-graduation-alerts': {
      id: '/api/public/check-graduation-alerts'
      path: '/api/public/check-graduation-alerts'
      fullPath: '/api/public/check-graduation-alerts'
      preLoaderRoute: typeof ApiPublicCheckGraduationAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/financeiro/mensalidades': {
      id: '/_authenticated/financeiro/mensalidades'
      path: '/mensalidades'
      fullPath: '/financeiro/mensalidades'
      preLoaderRoute: typeof AuthenticatedFinanceiroMensalidadesRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/alunos/novo': {
      id: '/_authenticated/alunos/novo'
      path: '/alunos/novo'
      fullPath: '/alunos/novo'
      preLoaderRoute: typeof AuthenticatedAlunosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alunos/$alunoId': {
      id: '/_authenticated/alunos/$alunoId'
      path: '/alunos/$alunoId'
      fullPath: '/alunos/$alunoId'
      preLoaderRoute: typeof AuthenticatedAlunosAlunoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroMensalidadesRoute: typeof AuthenticatedFinanceiroMensalidadesRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroMensalidadesRoute:
      AuthenticatedFinanceiroMensalidadesRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAfiliacoesRoute: typeof AuthenticatedAfiliacoesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedInstrutoresRoute: typeof AuthenticatedInstrutoresRoute
  AuthenticatedPresencaRoute: typeof AuthenticatedPresencaRoute
  AuthenticatedTurmasRoute: typeof AuthenticatedTurmasRoute
  AuthenticatedAlunosAlunoIdRoute: typeof AuthenticatedAlunosAlunoIdRoute
  AuthenticatedAlunosNovoRoute: typeof AuthenticatedAlunosNovoRoute
  AuthenticatedAlunosIndexRoute: typeof AuthenticatedAlunosIndexRoute
  AuthenticatedRelatoriosIndexRoute: typeof AuthenticatedRelatoriosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAfiliacoesRoute: AuthenticatedAfiliacoesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedInstrutoresRoute: AuthenticatedInstrutoresRoute,
  AuthenticatedPresencaRoute: AuthenticatedPresencaRoute,
  AuthenticatedTurmasRoute: AuthenticatedTurmasRoute,
  AuthenticatedAlunosAlunoIdRoute: AuthenticatedAlunosAlunoIdRoute,
  AuthenticatedAlunosNovoRoute: AuthenticatedAlunosNovoRoute,
  AuthenticatedAlunosIndexRoute: AuthenticatedAlunosIndexRoute,
  AuthenticatedRelatoriosIndexRoute: AuthenticatedRelatoriosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroAcademiaRoute: CadastroAcademiaRoute,
  LoginRoute: LoginRoute,
  ApiPublicCheckGraduationAlertsRoute: ApiPublicCheckGraduationAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
